### PR TITLE
Patch: Update easylist for Google Sign-In to work

### PR DESCRIPTION
**Pull request by Kokobe**
Found that easylist.txt contained rules that messed with sign in with Google: `@@||accounts.google.com^`. 

Deleted those lines and now Sign-In with Google works when Strict Mode + Adblocking is on. 

Updated the documentation so that we know to delete these lines whenever updating easylist. https://paper.dropbox.com/doc/Android-updating-easylist-files-in-WebLayer--BrOIOt~XJq1ZEBGczjXzzuE1Ag-N7Ov3syRhK0B92hp8wXGi

### CODE REVIEW

**Comment by chung-lai** [comment]
The files are too large to view so I believe you updated the files and deleted the two google offending rules. 😏 

Couple follow-ups we should do here:

* To me, this is more like a patch. For the long run, if the reason google sign in is failing because we don't respect the filter options `popup` or `generichide`, then we should look and see how to support them. Pretty sure other rules that have those filter option will fail some other sites down the road. We should try to fix the root cause if possible. (May be file a click up?)
* Instead of manually removing them, may be it's better to write a simple script with `sed` or `awk` to do the replacement so it's less error prone. Alternatively, if it's feasible, may be it can be part of `make_filter_rules`

**Comment by chung-lai** [comment]
btw, thanks for looking into this, @Kokobe!!

**Review by chung-lai — APPROVED** [review]
The change looks good in the PR but we should try to follow up to figure out the root problem.

**Comment by Kokobe** [comment]
Added a click-up task! https://app.clickup.com/t/37bnk4z

**Pull request merged**
